{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quicklearner-frontend.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "quicklearner-frontend.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
