export type CurriculumDay = {
  day: number
  title: string
  topics: string[]
  lab: string
}

export type Course = {
  id: string
  title: string
  duration: string
  students: number
  rating: number
  category: string
  color: string
  emoji: string
  description: string
  highlights: string[]
  outcomes: string[]
  curriculum: CurriculumDay[]
}

const curriculum = (days: Array<Omit<CurriculumDay, 'day'>>): CurriculumDay[] =>
  days.map((day, index) => ({ ...day, day: index + 1 }))

const commonHighlights = [
  'Live mentor-led sessions',
  'Project-based assignments',
  'Resume and interview preparation',
  'Internship and placement guidance',
]

export const courses: Course[] = [
  {
    id: 'python-fullstack',
    title: 'Python Full Stack',
    duration: '12 weeks',
    students: 320,
    rating: 4.8,
    category: 'Development',
    color: '#dc2626',
    emoji: '🐍',
    description: 'Python, Django, Flask, React, MySQL, MongoDB, REST APIs and AWS deployment.',
    highlights: commonHighlights,
    outcomes: ['Build full-stack web apps', 'Create REST APIs', 'Connect frontend with backend', 'Deploy production-ready applications'],
    curriculum: curriculum([
      { title: 'Python & web development roadmap', topics: ['Course orientation', 'Web architecture', 'Frontend vs backend', 'Developer workflow'], lab: 'Set up VS Code, Git, Python and first repository' },
      { title: 'Python fundamentals', topics: ['Variables', 'Data types', 'Conditions', 'Loops'], lab: 'Build command-line mini programs' },
      { title: 'Functions and file handling', topics: ['Functions', 'Modules', 'Exceptions', 'File operations'], lab: 'Create a file-based student record system' },
      { title: 'Object-oriented Python', topics: ['Classes', 'Objects', 'Inheritance', 'Encapsulation'], lab: 'Model a course enrollment system' },
      { title: 'Databases with SQL', topics: ['Tables', 'CRUD', 'Joins', 'Relationships'], lab: 'Design course and student database tables' },
      { title: 'Django and Flask basics', topics: ['Routes', 'Views', 'Templates', 'Project structure'], lab: 'Create a basic institute website backend' },
      { title: 'REST API development', topics: ['HTTP methods', 'Serializers', 'API routing', 'Status codes'], lab: 'Build course enquiry APIs' },
      { title: 'React fundamentals', topics: ['Components', 'Props', 'State', 'Hooks'], lab: 'Create reusable course cards' },
      { title: 'Frontend-backend integration', topics: ['Fetch API', 'Forms', 'Validation', 'Error handling'], lab: 'Connect enquiry form with backend API' },
      { title: 'Authentication and authorization', topics: ['Login flow', 'JWT basics', 'Protected routes', 'User roles'], lab: 'Add student/admin login flow' },
      { title: 'Testing and deployment', topics: ['API testing', 'Build process', 'Environment variables', 'Cloud deployment'], lab: 'Deploy app with frontend and backend environment variables' },
      { title: 'Capstone and interview prep', topics: ['Portfolio review', 'Mock interview', 'GitHub profile', 'Project explanation'], lab: 'Complete and present a full-stack capstone project' },
    ]),
  },
  {
    id: 'mern-stack',
    title: 'MERN Stack',
    duration: '12 weeks',
    students: 280,
    rating: 4.9,
    category: 'Development',
    color: '#b91c1c',
    emoji: '⚛️',
    description: 'MongoDB, Express, React, Node.js, REST APIs, authentication and cloud deployment.',
    highlights: commonHighlights,
    outcomes: ['Build MERN applications', 'Create secure APIs', 'Use MongoDB effectively', 'Deploy scalable web projects'],
    curriculum: curriculum([
      { title: 'MERN architecture overview', topics: ['Client-server model', 'Node runtime', 'React SPA', 'MongoDB documents'], lab: 'Set up Node, React and Git workflow' },
      { title: 'JavaScript essentials', topics: ['ES6 syntax', 'Arrays', 'Objects', 'Async basics'], lab: 'Solve JavaScript logic tasks' },
      { title: 'Node.js fundamentals', topics: ['Modules', 'NPM', 'Events', 'Environment variables'], lab: 'Create a Node utility project' },
      { title: 'Express API development', topics: ['Routing', 'Controllers', 'Middleware', 'Error handling'], lab: 'Build course listing APIs' },
      { title: 'MongoDB and Mongoose', topics: ['Schemas', 'Models', 'Queries', 'Validation'], lab: 'Create students and enquiries collections' },
      { title: 'React components and hooks', topics: ['Components', 'Props', 'useState', 'useEffect'], lab: 'Build responsive course listing UI' },
      { title: 'API integration', topics: ['Axios/fetch', 'Loading states', 'Form handling', 'Toast messages'], lab: 'Submit enquiry data to Express API' },
      { title: 'Authentication', topics: ['Password hashing', 'JWT', 'Protected routes', 'Role-based access'], lab: 'Build login and admin access' },
      { title: 'State and routing', topics: ['React Router', 'Context API', 'Reusable layouts', 'Navigation'], lab: 'Create student dashboard pages' },
      { title: 'Uploads and advanced APIs', topics: ['File upload', 'Search', 'Pagination', 'Filtering'], lab: 'Add searchable course catalog' },
      { title: 'Testing and deployment', topics: ['Postman', 'Build optimization', 'Environment setup', 'Hosting'], lab: 'Deploy MERN app frontend and backend' },
      { title: 'Capstone review', topics: ['Code review', 'Project demo', 'Interview questions', 'Resume points'], lab: 'Present a production-style MERN capstone' },
    ]),
  },
  {
    id: 'data-science',
    title: 'Data Science',
    duration: '12 weeks',
    students: 410,
    rating: 4.7,
    category: 'Data',
    color: '#ef4444',
    emoji: '📊',
    description: 'Python, statistics, data cleaning, machine learning, visualization and model deployment.',
    highlights: commonHighlights,
    outcomes: ['Analyze real datasets', 'Build ML models', 'Create dashboards', 'Explain insights for business use cases'],
    curriculum: curriculum([
      { title: 'Data science roadmap', topics: ['Roles', 'Tools', 'Project lifecycle', 'Dataset types'], lab: 'Set up Python, Jupyter and data workspace' },
      { title: 'Python for data', topics: ['Lists', 'Dictionaries', 'Functions', 'Packages'], lab: 'Analyze simple CSV files' },
      { title: 'NumPy and Pandas', topics: ['Arrays', 'DataFrames', 'Filtering', 'Aggregation'], lab: 'Clean and summarize student performance data' },
      { title: 'Data cleaning', topics: ['Missing values', 'Duplicates', 'Outliers', 'Data types'], lab: 'Prepare raw sales dataset for analysis' },
      { title: 'Statistics basics', topics: ['Mean/median', 'Variance', 'Probability', 'Distributions'], lab: 'Create descriptive statistics report' },
      { title: 'Visualization', topics: ['Matplotlib', 'Seaborn concepts', 'Charts', 'Storytelling'], lab: 'Build charts for business insights' },
      { title: 'Machine learning intro', topics: ['Train/test split', 'Regression', 'Classification', 'Metrics'], lab: 'Train first prediction model' },
      { title: 'Feature engineering', topics: ['Encoding', 'Scaling', 'Feature selection', 'Pipelines'], lab: 'Improve model accuracy using feature engineering' },
      { title: 'Advanced ML', topics: ['Decision trees', 'Random forest', 'Clustering', 'Model tuning'], lab: 'Compare multiple algorithms' },
      { title: 'Model evaluation', topics: ['Confusion matrix', 'Precision/recall', 'RMSE', 'Overfitting'], lab: 'Prepare model performance summary' },
      { title: 'Model deployment basics', topics: ['Pickle/joblib', 'Flask API', 'Input validation', 'Deployment flow'], lab: 'Serve ML prediction API' },
      { title: 'Capstone and portfolio', topics: ['Problem framing', 'Notebook cleanup', 'GitHub README', 'Interview prep'], lab: 'Present end-to-end data science project' },
    ]),
  },
  {
    id: 'ai-ml',
    title: 'AI & Machine Learning',
    duration: '12 weeks',
    students: 390,
    rating: 4.9,
    category: 'AI',
    color: '#991b1b',
    emoji: '🤖',
    description: 'Supervised learning, unsupervised learning, neural networks, NLP and applied AI projects.',
    highlights: commonHighlights,
    outcomes: ['Understand ML workflows', 'Build AI models', 'Work with NLP use cases', 'Deploy AI-powered applications'],
    curriculum: curriculum([
      { title: 'AI/ML foundations', topics: ['AI vs ML vs DL', 'Use cases', 'Model lifecycle', 'Tools'], lab: 'Set up Python ML environment' },
      { title: 'Python and math essentials', topics: ['Linear algebra basics', 'Probability', 'Functions', 'Data structures'], lab: 'Implement simple vector operations' },
      { title: 'Data preparation', topics: ['Cleaning', 'Encoding', 'Scaling', 'Train/test split'], lab: 'Prepare dataset for ML training' },
      { title: 'Supervised learning', topics: ['Regression', 'Classification', 'Loss functions', 'Metrics'], lab: 'Build house price and churn models' },
      { title: 'Unsupervised learning', topics: ['Clustering', 'Dimensionality reduction', 'Segmentation', 'Use cases'], lab: 'Create customer segmentation model' },
      { title: 'Model tuning', topics: ['Cross validation', 'Hyperparameters', 'Grid search', 'Bias variance'], lab: 'Tune and compare ML models' },
      { title: 'Neural network basics', topics: ['Perceptron', 'Activation functions', 'Backpropagation', 'Epochs'], lab: 'Train a simple neural network' },
      { title: 'Deep learning concepts', topics: ['CNN basics', 'Embeddings', 'Transfer learning', 'Evaluation'], lab: 'Image classification mini project' },
      { title: 'NLP fundamentals', topics: ['Text cleaning', 'Tokenization', 'Vectorization', 'Sentiment analysis'], lab: 'Build sentiment analysis model' },
      { title: 'Applied AI workflows', topics: ['Prompting basics', 'AI app design', 'Model APIs', 'Responsible AI'], lab: 'Create AI assistant style demo' },
      { title: 'Deployment', topics: ['Flask/FastAPI', 'Model serving', 'Monitoring basics', 'Cloud options'], lab: 'Expose trained model through API' },
      { title: 'Capstone and interviews', topics: ['Project story', 'Evaluation explanation', 'Resume framing', 'Mock interview'], lab: 'Present AI/ML capstone project' },
    ]),
  },
  {
    id: 'cybersecurity',
    title: 'Cybersecurity',
    duration: '12 weeks',
    students: 210,
    rating: 4.8,
    category: 'Security',
    color: '#7f1d1d',
    emoji: '🔐',
    description: 'Networking, Linux security, ethical hacking basics, SIEM, web security and ISO security practices.',
    highlights: commonHighlights,
    outcomes: ['Understand security fundamentals', 'Perform safe lab-based testing', 'Use SIEM workflows', 'Prepare for security analyst roles'],
    curriculum: curriculum([
      { title: 'Cybersecurity roadmap', topics: ['Security roles', 'CIA triad', 'Threat landscape', 'Lab ethics'], lab: 'Set up safe local security lab' },
      { title: 'Networking fundamentals', topics: ['TCP/IP', 'Ports', 'DNS', 'HTTP/HTTPS'], lab: 'Analyze packets and network flow' },
      { title: 'Linux and Windows security', topics: ['Users', 'Permissions', 'Logs', 'Hardening basics'], lab: 'Review system logs and permissions' },
      { title: 'Web security basics', topics: ['OWASP overview', 'Authentication', 'Input validation', 'Sessions'], lab: 'Identify common demo app weaknesses' },
      { title: 'Vulnerability assessment', topics: ['Scanning concepts', 'CVEs', 'Risk rating', 'Reporting'], lab: 'Run controlled vulnerability scan in lab' },
      { title: 'Secure coding awareness', topics: ['Injection', 'XSS', 'Broken auth', 'Secure headers'], lab: 'Fix vulnerable code patterns' },
      { title: 'SIEM fundamentals', topics: ['Log sources', 'Correlation', 'Alerts', 'Dashboards'], lab: 'Create basic security monitoring view' },
      { title: 'Incident response', topics: ['Triage', 'Containment', 'Evidence', 'Communication'], lab: 'Write incident response runbook' },
      { title: 'Cloud security', topics: ['IAM', 'Security groups', 'Storage security', 'Monitoring'], lab: 'Review cloud security checklist' },
      { title: 'Governance and ISO practices', topics: ['Policies', 'Controls', 'Audit evidence', 'Risk management'], lab: 'Map controls to institute security process' },
      { title: 'Security project', topics: ['Assessment report', 'Findings', 'Remediation plan', 'Executive summary'], lab: 'Prepare professional security report' },
      { title: 'Interview preparation', topics: ['SOC questions', 'Web security questions', 'Scenario handling', 'Resume review'], lab: 'Mock security analyst interview' },
    ]),
  },
  {
    id: 'data-analytics',
    title: 'Data Analytics',
    duration: '12 weeks',
    students: 340,
    rating: 4.7,
    category: 'Data',
    color: '#f87171',
    emoji: '📈',
    description: 'Excel, SQL, Power BI, Tableau, Python basics and business analytics storytelling.',
    highlights: commonHighlights,
    outcomes: ['Create dashboards', 'Write SQL queries', 'Clean business data', 'Present insights clearly'],
    curriculum: curriculum([
      { title: 'Analytics career roadmap', topics: ['Analyst roles', 'Tools', 'Business metrics', 'Case studies'], lab: 'Set up Excel, SQL and BI workspace' },
      { title: 'Excel fundamentals', topics: ['Formulas', 'Formatting', 'Tables', 'Data validation'], lab: 'Create student admissions tracker' },
      { title: 'Advanced Excel', topics: ['Pivot tables', 'Lookups', 'Charts', 'Power Query'], lab: 'Build sales analysis workbook' },
      { title: 'SQL basics', topics: ['SELECT', 'WHERE', 'ORDER BY', 'Aggregations'], lab: 'Query customer and course data' },
      { title: 'SQL joins and reporting', topics: ['Joins', 'Group by', 'Subqueries', 'Views'], lab: 'Create monthly performance report' },
      { title: 'Power BI fundamentals', topics: ['Data import', 'Relationships', 'Visuals', 'Filters'], lab: 'Create first Power BI dashboard' },
      { title: 'DAX and dashboard design', topics: ['Measures', 'KPIs', 'Cards', 'Slicers'], lab: 'Build placement performance dashboard' },
      { title: 'Tableau basics', topics: ['Charts', 'Calculated fields', 'Dashboards', 'Stories'], lab: 'Create interactive Tableau view' },
      { title: 'Python for analysts', topics: ['Pandas basics', 'Data cleaning', 'Simple charts', 'Exporting reports'], lab: 'Clean dataset using Python' },
      { title: 'Business storytelling', topics: ['Insight writing', 'Executive summary', 'Recommendations', 'Presentation flow'], lab: 'Prepare dashboard presentation' },
      { title: 'Analytics capstone', topics: ['Problem statement', 'Data model', 'Dashboard review', 'Insights'], lab: 'Complete end-to-end analytics project' },
      { title: 'Interview preparation', topics: ['SQL interview questions', 'Dashboard explanation', 'Resume projects', 'Mock interview'], lab: 'Present portfolio and answer case questions' },
    ]),
  },
  {
    id: 'java-fullstack',
    title: 'Java Full Stack',
    duration: '12 weeks',
    students: 260,
    rating: 4.6,
    category: 'Development',
    color: '#dc2626',
    emoji: '☕',
    description: 'Core Java, Spring Boot, SQL, REST APIs, HTML, CSS, JavaScript and deployment basics.',
    highlights: commonHighlights,
    outcomes: ['Build Spring Boot APIs', 'Understand Java OOP', 'Connect UI with backend', 'Prepare enterprise app projects'],
    curriculum: curriculum([
      { title: 'Java roadmap and setup', topics: ['JDK', 'IDE setup', 'Build tools', 'Project structure'], lab: 'Create first Java project' },
      { title: 'Core Java basics', topics: ['Variables', 'Loops', 'Arrays', 'Methods'], lab: 'Solve Java programming tasks' },
      { title: 'OOP in Java', topics: ['Classes', 'Objects', 'Inheritance', 'Polymorphism'], lab: 'Build student/course model' },
      { title: 'Collections and exceptions', topics: ['List', 'Map', 'Set', 'Exception handling'], lab: 'Create enrollment management logic' },
      { title: 'SQL and JDBC basics', topics: ['CRUD', 'Joins', 'JDBC connection', 'DAO pattern'], lab: 'Connect Java app with database' },
      { title: 'Spring Boot intro', topics: ['Starters', 'Controllers', 'Services', 'Configuration'], lab: 'Create first Spring Boot API' },
      { title: 'REST API development', topics: ['Request mapping', 'DTOs', 'Validation', 'Error handling'], lab: 'Build course enquiry API' },
      { title: 'JPA and Hibernate', topics: ['Entities', 'Repositories', 'Relationships', 'Queries'], lab: 'Persist student records with JPA' },
      { title: 'Frontend basics', topics: ['HTML', 'CSS', 'JavaScript', 'Forms'], lab: 'Build course enquiry UI' },
      { title: 'Frontend-backend integration', topics: ['Fetch API', 'JSON', 'CORS', 'Validation'], lab: 'Connect UI to Spring API' },
      { title: 'Testing and deployment', topics: ['Unit tests', 'API tests', 'Build JAR', 'Cloud deployment'], lab: 'Deploy Spring Boot application' },
      { title: 'Capstone and interviews', topics: ['Project review', 'Java interview questions', 'Spring scenarios', 'Resume prep'], lab: 'Present Java full-stack capstone' },
    ]),
  },
  {
    id: 'cloud-computing',
    title: 'Cloud Computing',
    duration: '8 weeks',
    students: 180,
    rating: 4.7,
    category: 'Cloud',
    color: '#be123c',
    emoji: '☁️',
    description: 'AWS, Azure/GCP basics, Linux, Docker, Kubernetes, DevOps workflows and cloud deployment.',
    highlights: commonHighlights,
    outcomes: ['Understand cloud services', 'Deploy apps on cloud', 'Use containers', 'Prepare for cloud support and DevOps roles'],
    curriculum: curriculum([
      { title: 'Cloud roadmap', topics: ['IaaS/PaaS/SaaS', 'Regions', 'Availability zones', 'Shared responsibility'], lab: 'Create cloud account and understand console basics' },
      { title: 'Linux essentials', topics: ['Commands', 'Files', 'Processes', 'Permissions'], lab: 'Deploy simple app on Linux VM' },
      { title: 'AWS compute and storage', topics: ['EC2', 'EBS', 'S3', 'AMI basics'], lab: 'Launch EC2 and host static page' },
      { title: 'Networking fundamentals', topics: ['VPC', 'Subnets', 'Routing', 'Security groups'], lab: 'Create public/private subnet design' },
      { title: 'IAM and security', topics: ['Users', 'Roles', 'Policies', 'Least privilege'], lab: 'Create secure access policy' },
      { title: 'Databases and monitoring', topics: ['RDS basics', 'CloudWatch', 'Logs', 'Alerts'], lab: 'Monitor application health' },
      { title: 'Docker basics', topics: ['Images', 'Containers', 'Dockerfile', 'Registry'], lab: 'Containerize sample web app' },
      { title: 'Kubernetes overview', topics: ['Pods', 'Deployments', 'Services', 'Ingress'], lab: 'Deploy containerized app to Kubernetes' },
      { title: 'CI/CD basics', topics: ['Git', 'Build pipeline', 'Deployment pipeline', 'Rollback'], lab: 'Create simple GitHub Actions workflow' },
      { title: 'Infrastructure as code', topics: ['Terraform basics', 'State', 'Modules', 'Plan/apply'], lab: 'Provision a simple cloud resource' },
      { title: 'Capstone project', topics: ['Architecture', 'Deployment', 'Monitoring', 'Documentation'], lab: 'Deploy cloud-ready full-stack application' },
      { title: 'Interview preparation', topics: ['AWS scenarios', 'Linux questions', 'Docker/K8s basics', 'Resume review'], lab: 'Mock cloud interview' },
    ]),
  },
  {
    id: 'digital-marketing',
    title: 'Digital Marketing',
    duration: '12 weeks',
    students: 290,
    rating: 4.6,
    category: 'Marketing',
    color: '#e11d48',
    emoji: '📱',
    description: 'SEO, SEM, social media marketing, email campaigns, content strategy and analytics.',
    highlights: commonHighlights,
    outcomes: ['Run digital campaigns', 'Improve SEO visibility', 'Analyze marketing data', 'Create content and ad strategy'],
    curriculum: curriculum([
      { title: 'Digital marketing roadmap', topics: ['Channels', 'Funnels', 'Audience', 'Brand positioning'], lab: 'Create marketing strategy for a sample brand' },
      { title: 'Website and landing pages', topics: ['Landing page structure', 'CTA', 'Copywriting', 'Conversion basics'], lab: 'Design landing page wireframe' },
      { title: 'SEO fundamentals', topics: ['Keywords', 'On-page SEO', 'Technical SEO', 'Search intent'], lab: 'Prepare keyword research sheet' },
      { title: 'Content marketing', topics: ['Content calendar', 'Blog structure', 'Brand voice', 'Repurposing'], lab: 'Create 30-day content plan' },
      { title: 'Social media marketing', topics: ['Instagram', 'LinkedIn', 'YouTube', 'Engagement strategy'], lab: 'Design social campaign plan' },
      { title: 'Paid ads basics', topics: ['Google Ads', 'Meta Ads', 'Campaign objectives', 'Budgeting'], lab: 'Create sample ad campaign structure' },
      { title: 'Email marketing', topics: ['Lists', 'Segmentation', 'Templates', 'Automation'], lab: 'Build nurture email sequence' },
      { title: 'Analytics', topics: ['Google Analytics basics', 'UTM tracking', 'KPIs', 'Reporting'], lab: 'Create marketing performance dashboard' },
      { title: 'Lead generation', topics: ['Lead magnets', 'Forms', 'CRM basics', 'Follow-up flow'], lab: 'Plan lead generation funnel' },
      { title: 'Personal branding', topics: ['LinkedIn profile', 'Portfolio', 'Case studies', 'Freelancing basics'], lab: 'Optimize LinkedIn and portfolio outline' },
      { title: 'Campaign capstone', topics: ['Strategy', 'Creatives', 'Analytics', 'Recommendations'], lab: 'Present full campaign plan' },
      { title: 'Interview and client pitch', topics: ['Marketing questions', 'Portfolio explanation', 'Pitching', 'Reporting'], lab: 'Mock client pitch and interview' },
    ]),
  },
]

export const getCourseById = (id: string) => courses.find(course => course.id === id)
